config/routes.rb
Rails.application.routes.draw do
  resources :classrooms

  resources :courses

  resources :students
  root to: 'students#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :course
  belongs_to :student
  validates :course_id, :student_id, presence: { message: " é obrigatório" }

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :classrooms, :dependent => :destroy 
    validates :status, presence:  { message: " é obrigatório" }
    validates :name, :description, presence:  { message: " é obrigatório" }, length: { maximum: 45 }
end

app/models/course_status.rb
class CourseStatus < ActiveRecord::Base
    validates :name, presence:  { message: " é obrigatório" }
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :classrooms, :dependent => :destroy 
    validates :status, presence:  { message: " é obrigatório" }
    validates :name, :register_number, presence:  { message: " é obrigatório" }, length: { maximum: 45 }
    def self.search(query)
    	where("name like ?","%#{query}%")
    end
end

app/models/student_status.rb
class StudentStatus < ActiveRecord::Base
    validates :name, presence: { message: " é obrigatório" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  # GET /classrooms
  def index
    @classrooms = Classroom.all
    @students = Student.all
    @courses = Course.all
  end

  # GET /classrooms/1
  def show
    @classrooms = Classroom.all
    @students = Student.all
    @courses = Course.all
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
    @classrooms = Classroom.all
    @students = Student.all
    @courses = Course.all
  end

  # GET /classrooms/1/edit
  def edit
    @classrooms = Classroom.all
    @students = Student.all
    @courses = Course.all
  end

  # POST /classrooms
  def create
    @classroom = Classroom.new(classroom_params)
    @classroom.entry_at = Time.now

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to classrooms_url, notice: 'Classroom criada com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to classrooms_url, notice: 'Classroom atualizada com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: 'Classroom removida com sucesso.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = classroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_params
      params.require(:classroom).permit(:name, :student_id, :course_id, :entry_at)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  def index
    @courses = Course.all
    @coursestatus = CourseStatus.all
  end

  # GET /courses/new
  def new
    @course = Course.new
    @coursestatus = CourseStatus.all
  end

  # GET /courses/1/edit
  def edit
     @coursestatus = CourseStatus.all
  end

  # POST /courses
  def create
    @coursestatus = CourseStatus.all
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to courses_url, notice: 'course criada com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    @coursestatus = CourseStatus.all
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to courses_url, notice: 'course atualizada com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /courses/1
  def destroy
    @coursestatus = CourseStatus.all
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'course removida com sucesso.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :status)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  def index
    @students = Student.all
    @studentstatuses = StudentStatus.all
    if params[:search]
      @students = Student.search(params[:search]).order(name: :desc)
    else
      @students = Student.order(name: :desc)
    end
  end


  # GET /students/new
  def new
    @student = Student.new
    @studentstatuses = StudentStatus.all
  end

  # GET /students/1/edit
  def edit
    @studentstatuses = StudentStatus.all
  end

  # POST /students
  def create
    @studentstatuses = StudentStatus.all
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to students_url, notice: 'Estudante criado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /students/1
  def update
    @studentstatuses = StudentStatus.all
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to students_url, notice: 'Estudante atualizado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /students/1
  def destroy
    @studentstatuses = StudentStatus.all
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Estudante apagado com sucesso!' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :register_number, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/classrooms/_form.html.erb
<%= form_for(@classroom) do |f| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom.errors.count, "erro") %> esta matrícula não pode ser salva:</h2>

      <ul>
      <% @classroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <div class="col-md-4">
    <%= f.label :student_id %><br>
    <%= collection_select(:classroom, :student_id, @students, :id, :name, {prompt: true}, {:class=>'form-control form-group'})%>
    <%= f.label :course_id %><br>
    <%= collection_select(:classroom, :course_id, @courses, :id, :name, {prompt: true}, {:class=>'form-control form-group'})%>
  </div>
</div>
<div class="form-group">
  <div class="col-md-12">
    <br>
    <%= f.submit  class: "btn btn-success form-group-sm" %>
    <%= link_to classrooms_path, :class => "btn btn-danger form-group-sm" do %>
        <i class="fa fa-undo"></i><% end %>
  </div>
  </div>
<% end %>

app/views/classrooms/edit.html.erb
<h1>Editando Matrícula</h1>

<%= render 'form' %>

app/views/classrooms/index.html.erb
<h2>Matrículas</h2>
  <div class="col-md-12 white-bg well">
  <a href="/classrooms/new" class="btn btn-success">
      Nova Matrícula <i class="fa fa-plus"> </i></a>
    <hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Estudante</th>
      <th>Curso</th>
      <th>Matriculado em:</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><strong><%= classroom.id %></strong></td>
        <td><%= classroom.student.name %></td>
        <td><%= classroom.course.name %></td>
        <td><%= classroom.entry_at.strftime("%d/%m/%Y - %H:%M:%S") %></td>
        <td><div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <i class="fa fa-cog"></i> <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">       
              <li><%= link_to edit_classroom_path(classroom) do %><i class="fa fa-pencil-square-o"></i><% end %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to  classroom, method: :delete, data: { confirm: 'Você tem certeza?' } do %><i class="fa fa-trash"></i><% end %></li>
            </ul>
          </div>
        </td>
      </tr>
     <% end %>
  </tbody>
</table>
</div>

app/views/classrooms/new.html.erb
<h1>Nova Matrícula</h1>

<%= render 'form' %>

app/views/classrooms/show.html.erb
<div class="col-md-12 white-bg well"><div class="col-md-6">
<p>
  <h2> <%= @student.name %></h2>
</p>

<p>
  <strong>Registro Nº:</strong><br>
  <%= @student.register_number %>
</p>

<p>
  <strong>Status:</strong>
  <%= @student.status %>
</p>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "erro") %> este curso não pode ser salvo</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <div class="col-md-4">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class =>  "form-control input-md" %>
    <%= f.label :description %><br>
    <%= f.text_field :description, :class =>  "form-control input-md" %>
    <%= f.label :status %><br>
    <%= collection_select(:course, :status, @coursestatus, :id, :name,  {prompt: true}, {:class=>'form-control form-group'}) %>
  </div>
</div>
<div class="form-group">
  <div class="col-md-12">
    <br>
    <%= f.submit  class: "btn btn-success form-group-sm" %>
    <%= link_to courses_path, :class => "btn btn-danger form-group-sm" do %>
        <i class="fa fa-undo"></i><% end %>
  </div>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editando Curso</h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<h2>Cursos</h2>
  <div class="col-md-12 white-bg well">
  <a href="/courses/new" class="btn btn-success">
      Novo curso <i class="fa fa-plus"> </i></a>
    <hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Status</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><strong><%= course.id %></strong></td>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><%= course.status %></td>
        <td><div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <i class="fa fa-cog"></i> <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">       
              <li><%= link_to edit_course_path(course) do %><i class="fa fa-pencil-square-o"></i><% end %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to  course, method: :delete, data: { confirm: 'Você tem certeza?' } do %><i class="fa fa-trash"></i><% end %></li>
            </ul>
          </div>
        </td>
      </tr>
     <% end %>
  </tbody>
</table>
</div>

app/views/courses/new.html.erb
<h1>Novo Curso</h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<div class="col-md-12 white-bg well"><div class="col-md-6">
<p>
  <h2> <%= @course.name %></h2>
</p>

<p>
  <strong>Registro Nº:</strong><br>
  <%= @course.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @course.status %>
</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= form_tag(students_path, :method => :get) do%>
<div class="painel-left">
  <div class="painel-up">          
    <div class="col-md-6">
      <div class="inner-addon left-addon">
      <i class="fa fa-search"></i>      
      <%= text_field_tag 'search', nil, placeholder: "Pesquisar estudantes...", :class =>  "form-control" %>
       <%end%>
    </div>
  </div>
  </div> 
</div>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper"align="center">
  <ul class="sidebar-nav" >
    <li class="brand">
     <h3>Proficiency Teste</h3>
    </li>
    <li class="">
      <a  href="/" class="btn-sidebar"><i class="fa fa-home fa-lg"></i> <span class="left-icon-sidebar"> Início</span></a>
    </li>
    <p></p>
    <li>
      <a href="javascript:;"  class="btn-sidebar sidebar-left-icon " data-toggle="collapse" data-target="#student"><i class="fa fa-users fa-lg "></i> <span class="left-icon-sidebar"> Estudantes </span><span class="caret"></span></a>
      <ul id="student" class="collapse" align="left" style="list-style-type: none;">
        <p></p>
        <li><a href="/students/" class="btn-sidebar-ul"><i class="fa fa-list fa-lg"></i> Ver Estudantes</a></li>
        <li><a href="/students/new" class="btn-sidebar-ul"><i class="fa fa-plus fa-lg"></i> Novo Estudante</a></li>
      </ul>
    </li>
    <p></p>
    <li>
      <a href="javascript:;"  class="btn-sidebar sidebar-left-icon " data-toggle="collapse" data-target="#team"><i class="fa fa-graduation-cap fa-lg "></i> <span class="left-icon-sidebar"> Cursos </span><span class="caret"></span></a>
      <ul id="team" class="collapse" align="left" style="list-style-type: none;">
        <p></p>
        <li><a href="/courses" class="btn-sidebar-ul"><i class="fa fa-list fa-lg"></i> Ver Cursos</a></li>
        <li><a href="/courses/new" class="btn-sidebar-ul"><i class="fa fa-plus fa-lg"></i> Novo Curso</a></li>
      </ul>
    </li>
    <p></p>
    <li>
      <a href="javascript:;"  class="btn-sidebar sidebar-left-icon " data-toggle="collapse" data-target="#employee"><i class="fa fa-users fa-lg "></i> <span class="left-icon-sidebar"> Matrículas </span><span class="caret"></span></a>
      <ul id="employee" class="collapse" align="left" style="list-style-type: none;">
        <p></p>
        <li><a href="/classrooms/" class="btn-sidebar-ul"><i class="fa fa-list fa-lg"></i> Ver Matrículas</a></li>
        <li><a href="/classrooms/new" class="btn-sidebar-ul"><i class="fa fa-plus fa-lg"></i> Nova Matrícula</a></li>
      </ul>
    </li>
    <p></p>
  </ul>
</div>
<!-- /#sidebar-wrapper -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Proficiency Test" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Proficiency Test" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  </head>
  <body>  
	<div id="wrapper">
	  <%= render 'layouts/sidebar' %>
	</div>
	<%= render 'layouts/navigation' %>
	<main role="main">
		<div id="wrapper">
		       <%= render 'layouts/messages' %>
		       <%= yield %>
		</div>
	</main>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-2.2.0.min.js" ></script>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "erro") %> este estudante não pode ser salvo:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <div class="col-md-4">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class =>  "form-control input-md" %>
    <%= f.label :register_number %><br>
    <%= f.text_field :register_number, :class =>  "form-control input-md" %>
    <%= f.label :status %><br>
    <%= collection_select(:student,:status,@studentstatuses,:id,:name, {prompt: true}, {:class=>'form-control form-group'}) %>
  </div>
</div>
<div class="form-group">
  <div class="col-md-12">
    <br>
    <%= f.submit  class: "btn btn-success form-group-sm" %>
    <%= link_to students_path, :class => "btn btn-danger form-group-sm" do %>
        <i class="fa fa-undo"></i><% end %>
  </div>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editando Estudante</h1>

<%= render 'form' %>

app/views/students/index.html.erb
<h2>Estudantes</h2>
  <div class="col-md-12 white-bg well">
  <a href="/students/new" class="btn btn-success">
      Adicionar Estudante <i class="fa fa-plus"> </i></a>
    <hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Nome</th>
      <th>Registro Nº</th>
      <th>Status</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><strong><%= student.id %></strong></td>
        <td><%= student.name %></td>
        <td><%= student.register_number %></td>
        <td><%= student.status %></td>
        <td><div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <i class="fa fa-cog"></i> <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">       
              <li><%= link_to edit_student_path(student) do %><i class="fa fa-pencil-square-o"></i><% end %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to  student, method: :delete, data: { confirm: 'Você tem certeza?' } do %><i class="fa fa-trash"></i><% end %></li>
            </ul>
          </div>
        </td>
      </tr>
     <% end %>
  </tbody>
</table>
</div>

app/views/students/new.html.erb
<h1>Novo Estudante</h1>

<%= render 'form' %>